In [1]:
install.packages("markovchain")
library(markovchain)

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

Loading required package: Matrix

Package:  markovchain
Version:  0.10.3
Date:     2026-02-02 06:30:37 UTC
BugReport: https://github.com/spedygiorgio/markovchain/issues

In [4]:
# Problem 2e

p = matrix(c(9/10,0,2/5,1/10,7/8,0,0,1/8,3/5), nrow=3, ncol=3)
p

for (i in 1:50){
    p = p%*%p
    }
p

     [,1] [,2]  [,3]
[1,] 0.9  0.100 0.000
[2,] 0.0  0.875 0.125
[3,] 0.4  0.000 0.600

     [,1]      [,2]      [,3]
[1,] 0.4870846 0.3896677 0.1217711
[2,] 0.4870846 0.3896677 0.1217711
[3,] 0.4870846 0.3896677 0.1217711

In [31]:
# Problem 2f

states = c("G", "S", "D")

p = matrix(c(9/10,0,2/5,1/10,7/8,0,0,1/8,3/5), nrow=3, ncol=3,
        dimnames = list(c("G", "S", "D"),
        c("G", "S", "D")))
#p

markov_chain = new("markovchain", states = states, transitionMatrix = p)
#markov_chain


N = 10000
simulate = rmarkovchain(n = N, object = markov_chain, t0 = "G")

table(simulate)

cat("The fraction of time spent in state G is: ", sum(simulate=="G")/N,"\n")


#steadyStates(markov_chain)

simulate
   D    G    S
1259 4660 4081

The fraction of time spent in state G is:  0.466

In [5]:
# Problem 3c

p = matrix(c(1,1/3,0,0,0, 0,0,1/3,0,0, 0,2/3,0,1/3,0, 0,0,2/3,0,0, 0,0,0,2/3,1), nrow=5, ncol=5)

p4 = p%*%p%*%p%*%p

p4[2,5]

[1] 0.2962963

In [42]:
# Problem 4c

states = c("1", "2", "3", "4", "5", "6")

p = matrix(c(1/2,0,1/3,0,0,0, 1/2,1/2,0,0,0,0, 0,1/2,1/3,0,0,0, 0,0,1/3,1/2,0,0, 0,0,0,1/2,0,1, 0,0,0,0,1,0), nrow=6, ncol=6,
        dimnames = list(c("1", "2", "3", "4", "5", "6"),
        c("1", "2", "3", "4", "5", "6")))
#p

markov_chain = new("markovchain", states = states, transitionMatrix = p)
#markov_chain

end_state = matrix(NA, nrow = 10000, ncol = 1)
for (i in 1:10000){
    N = 5
    simulate = rmarkovchain(n = N, object = markov_chain, t0 = "1")
    end_state[i] = simulate[5]
    }

sum(end_state == "4")
cat("The fraction of simulations in which the end state was 4 is: ", sum(end_state == "4")/10000,"\n")

[1] 1732

The fraction of simulations in which the end state was 4 is:  0.1732

In [10]:
# Problem 4d

p = matrix(c(1/2,0,1/3,0,0,0, 1/2,1/2,0,0,0,0, 0,1/2,1/3,0,0,0, 0,0,1/3,1/2,0,0, 0,0,0,1/2,0,1, 0,0,0,0,1,0), nrow=6, ncol=6)

for (i in 1:1000){
    p = p%*%p
    }
p

p[3,3]
p[1,1]
p[6,6]

# Problem 4f
p[1,4]
p[5,1]

     [,1] [,2] [,3] [,4] [,5]      [,6]
[1,] 0    0    0    0    0.5045045 0.4954955
[2,] 0    0    0    0    0.4864865 0.5135135
[3,] 0    0    0    0    0.5405405 0.4594595
[4,] 0    0    0    0    0.3333333 0.6666667
[5,] 0    0    0    0    1.0000000 0.0000000
[6,] 0    0    0    0    0.0000000 1.0000000

[1] 0

[1] 0

[1] 1

[1] 0

[1] 0